version: "3.9"

services:
  kltn-recommendation-service-be:
    container_name: kltn-recommendation-service-be
    # image: kltn-recommendation-service-be:${IMAGE_VERSION}
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "9094:8084"
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: 500M
