version: "3.9"

services:
  kltn-recommendation-service-be:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER_LOWERCASE}/kltn-recommendation-service-be:${IMAGE_VERSION}
    ports:
      - "9094:8084"
    env_file:
      - .env

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

      resources:
        limits:
          cpus: "0.2"
          memory: 500M

        reservations:
          cpus: "0.2"
          memory: 256M

      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
