version: "3.9"

services:
  kltn-recommendation-service-be:
    image: kltn-recommendation-service-be:${IMAGE_VERSION}
    ports:
      - "9094:8084"
    env_file:
      - .env

    restart: unless-stopped

    deploy:
      # replicas: 1

      # restart_policy:
      #   condition: on-failure

      resources:
        limits:
          cpus: "0.2"
          memory: 3G

        reservations:
          cpus: "0.2"
          memory: 1.5G

      # update_config:
      #   parallelism: 1
      #   delay: 10s
      #   order: stop-first

    volumes:
      - model_cache_data:/app/model_files

    networks:
      - kltn-shared-network

  kltn-recommendation-worker:
    image: kltn-recommendation-service-be:${IMAGE_VERSION}
    container_name: kltn-recommendation-worker
    # Không cần ports vì worker không lắng nghe HTTP request
    command: python worker/recommendation_worker.py
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5" # Worker cần nhiều CPU hơn để tính toán ma trận
          memory: 1G
        reservations:
          cpus: "0.3"
          memory: 500M
    networks:
      - kltn-shared-network

networks:
  kltn-shared-network:
    external: true

volumes:
  model_cache_data:
