name: real-estate-rec
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - fastapi
  - uvicorn
  - sqlalchemy
  - psycopg2 # Conda quản lý thư viện C binary tốt hơn cho Postgres
  - geoalchemy2
  - redis-py
  - pydantic
  - pip
