version: "3.9"

services:
  kltn-user-service-be:
    image: ghcr.io/${GITHUB_REPOSITORY_OWNER_LOWERCASE}/user-service-be:${IMAGE_VERSION}

    ports:
      - "127.0.0.1:9091:8080"

    env_file:
      - .env

    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure

      placement:
        constraints:
          - node.role == worker

      resources:
        limits:
          cpus: "0.8"
          memory: 700M

        reservations:
          cpus: "0.4"
          memory: 256M

      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first

    networks:
      - kltn-shared-network

networks:
  kltn-shared-network:
    external: true